version: '3.3'

services:
    mysqldb:
        image: mysql
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=SierraMikeEcho
        volumes:
        - mysql:/var/lib/mysql
        - mysql_config:/etc/mysql

    web:
        build:
          context: .
        depends_on:
        - 'mysqldb'
        ports:
        - 5000:5000
        volumes:
        - ./:/app

    localstack:
        image: localstack/localstack
        ports:
        - "4566:4566"
        - "4571:4571"
        - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
        environment:
        - SERVICES=kinesis
        - DEBUG=${DEBUG- }
        - DATA_DIR=${DATA_DIR- }
        - PORT_WEB_UI=${PORT_WEB_UI- }
        - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
        - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
        - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

volumes:
    mysql:
    mysql_config:
